restdoc:
#  host: 152.136.104.144
  host: 127.0.0.1
  port: 4321


dubbo:
  application:
    name: echo-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
#  monitor:
#    protocol: registry