restdoc:
#  host: 152.136.104.144
  host: 127.0.0.1
  port: 4321
  service: '客户端测试服务'


dubbo:
  application:
    name: echo-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
#  monitor:
#    protocol: registry
#// http://152.136.104.144:8432/restdoc/or/746946688983240704