restdoc:
  host: 127.0.0.1
  port: 4321
  service: dubbo


dubbo:
  application:
    name: boot-order-service-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
#  monitor:
#    protocol: registry